### ISSUE TITLE
Proof of concept checklist

### ISSUE THREAD

**Issue by rrnewton** [wangbj/systrace#1]
@wangbj has already taken this prototype pretty far.   Here's a checklist and what's left (feel free to edit/correct):

 * [x] trap syscalls in the original binary (bpf)
 * [x] in the signal handler, patch the offending instruction with a jump
 * [x] JIT code in a bpf "whitelisted" zone for the patched JMP to jump to (the trampoline)
 * [x] in the trampoline: place the relocated syscall instruction (*temporary*: this will eventually be the job of the handler function)
 * [x] in the trampoline: capture the register file to the stack
 * [ ] in the trampoline: set up a call to the handler function
 * [ ] in the trampoline: add a pointer to the register file as an argument before calling the handler function
 * [ ] in the trampoline: add global state / process state pointers to the handler function *also*

**Comment by rrnewton** [comment]
@gatoWololo - this is a place we need to sync up.  The low-level JITed code in the trampoline needs to match conventions on the memory layout of the structs pointed to by the arguments to the handler function. 

They will have *no* types in the low-level JIT'd code, but should have a matching type in the Rust code (with a corresponding pragma to control the layout).

**Comment by wangbj** [comment]
> in the trampoline: set up a call to the handler function
> in the trampoline: add a pointer to the register file as an argument before calling the handler function

This is already possible, you can modify below function:

https://github.com/iu-parfunc/systrace/blob/c6377541d3b377f8ea92794851fadfe0d609d3c8/src/syscallbuf.c#L80

i.e.: add a case for `SYS_openat`.

**Comment by rrnewton** [comment]
Great, check it off! ;-)
